config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  resources :journeys, only: [ :index,:new, :create, :show ] do
    resources :details, only: [ :new, :create ]
    resources :users, only: [ :new, :create ]
    resources :charges, only: [ :new, :create ]
  end

  devise_scope :user do
    get "/login" => "devise/sessions#new"
    delete '/logout', to: 'devise/sessions#destroy'
  end

  resources "contacts", only: [:new, :create]

  root to: 'journeys#new'

  # match '/sejour', to: 'details#new', via: 'get'
  match '/contacts', to: 'contacts#new', via: 'get'

  get 'pages/about'
  get 'pages/faq'
  get 'pages/confirmation'
  get 'pages/testimonials'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fa fa-github"></i></a>
    <a href="#"><i class="fa fa-instagram"></i></a>
    <a href="#"><i class="fa fa-facebook"></i></a>
    <a href="#"><i class="fa fa-twitter"></i></a>
    <a href="#"><i class="fa fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright">
    Réalisé avec <i class="fa fa-heart"></i> par le Coq Trotteur
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon navbar-fixed-top">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
    <%= image_tag "white-rooster.png" %>
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <!-- Links -->
    <%= link_to "EXPLICATIONS", root_path(anchor: "how-banner"), class: "navbar-wagon-item navbar-wagon-link" %>
    <%= link_to "OFFRIR UN CADEAU", root_path(anchor: "gift-banner"), class: "navbar-wagon-item navbar-wagon-link" %>
    <%= link_to "LES SÉJOURS", root_path(anchor: "info-banner"), class: "navbar-wagon-item navbar-wagon-link" %>
    <%= link_to "FAQ", pages_faq_path, class: "navbar-wagon-item navbar-wagon-link" %>
    <%= link_to "CONTACT", contacts_path, class: "navbar-wagon-item navbar-wagon-link" %>

    <!-- Avatar with dropdown menu -->
    <div class="navbar-wagon-item">
      <div class="dropdown">
        <% if user_signed_in? %>
          <%= link_to (image_tag "http://placehold.it/30x30", class: "avatar dropdown-toggle", id: "navbar-wagon-menu"), current_user.admin ? journeys_path : root_path %>
          <li>
            <%= link_to('Logout', destroy_user_session_path, method: :delete) %>
          </li>
        <% else %>
          <li>
            <%= link_to (image_tag "http://placehold.it/30x30", class: "avatar dropdown-toggle", id: "navbar-wagon-menu"), login_path %>
            <%= link_to('MON SÉJOUR', login_path) %>
          </li>
        <% end %>
      </div>
    </div>
  </div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><a href="#">Some mobile link</a></li>
        <li><a href="#">Other one</a></li>
        <li><a href="#">Other one</a></li>
      </ul>
    </div>
  </div>
</div>

app/views/shared/_steps.html.erb
<div id="step-bar">
  <div class="all-steps">
    <div class="step active-step">
      <p>☝</p>
      <h3>1 - Séjour</h3>
    </div>
    <div class="step">
      <p>✌</p>
      <h3>2 - Voyageurs</h3>
    </div>
    <div class="step">
      <p>👏</p>
      <h3>3 - Validation</h3>
    </div>
  </div>
  <div class="price">
    <h4><%= @journey.detail.price %></h4>
  </div>
</div>