config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  resources :journeys, only: [ :index,:new, :create, :show ] do
    resources :details, only: [ :new, :create ]
    resources :users, only: [ :new, :create ]
    resources :charges, only: [ :new, :create ]
  end

  devise_scope :user do
    get "/login" => "devise/sessions#new"
    delete '/logout', to: 'devise/sessions#destroy'
  end

  resources "contacts", only: [:new, :create]

  root to: 'journeys#new'

  # match '/sejour', to: 'details#new', via: 'get'
  match '/contacts', to: 'contacts#new', via: 'get'

  get 'pages/about'
  get 'pages/faq'
  get 'pages/confirmation'
  get 'pages/testimonials'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/journey.rb
class Journey < ApplicationRecord
  has_one :detail, dependent: :destroy
  has_one :user, dependent: :destroy

  validates :origin, :people_count, :destination_type, presence: true
end

app/controllers/journeys_controller.rb
class JourneysController < ApplicationController
  before_action :authenticate_user!, only: [ :index, :show ]

  def index
    if current_user.admin
      @journeys = policy_scope(Journey).order(created_at: :desc)
    else
      user_not_authorized
    end
  end

  def new
    @journey = Journey.new
    authorize @journey
  end

  def create
    @journey = Journey.new(journey_params)
    authorize @journey
    @journey.booking_ip = request.remote_ip
    @journey.status = "Journey created"

    number_of_people = @journey.people_count[/[123456789]/]
    @journey.update(people_count: number_of_people)

    if @journey.save
      redirect_to new_journey_detail_path(@journey)
    else
      render :new
    end
  end

  def show
    @journey = Journey.find(params[:id])
    authorize @journey
  end

  private

  def journey_params
      params.require(:journey).permit(:origin, :people_count, :destination_type)
  end
end

app/views/journeys/_client-info.html.erb
<!-- Modal -->
<div class="modal fade" id="myModal-<%= i %>" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h3 class="modal-title" id="exampleModalLabel">Réservé par <%= journey.client.name + " " + journey.client.surname %></h3>
      </div>
      <div class="modal-body">
        <div class="modal-block">
          <p><strong>Courriel :</strong></p>
          <p><strong>Sexe :</strong></p>
          <p><strong>Adresse :</strong></p>
          <p><strong>Date de naissance :</strong></p>
          <p><strong>Téléphone :</strong></p>
          <p><strong>Contact sms :</strong></p>
          <p><strong>Points d'attention :</strong></p>
        </div>
        <div class="modal-block">
          <p><%= journey.client.mail %></p>
          <p><%= journey.client.gender %></p>
          <p><%= journey.client.address %></p>
          <p><%= journey.client.birth_date %></p>
          <p><%= journey.client.phone %></p>
          <p><%= journey.client.contact ? "Non" : "Oui" %></p>
          <p><%= journey.detail.points_of_attention %></p>
        </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Fermer</button>
      </div>
    </div>
  </div>
</div>

app/views/journeys/_user-info.html.erb
<!-- Modal -->
<div class="modal fade" id="myModal-<%= i %>" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h3 class="modal-title" id="exampleModalLabel">Réservé par <%= journey.user.name + " " + journey.user.surname %></h3>
      </div>
      <div class="modal-body">
        <div class="modal-block">
          <p><strong>Courriel :</strong></p>
          <p><strong>Sexe :</strong></p>
          <p><strong>Adresse :</strong></p>
          <p><strong>Date de naissance :</strong></p>
          <p><strong>Téléphone :</strong></p>
          <p><strong>Contact sms :</strong></p>
          <p><strong>Points d'attention :</strong></p>
        </div>
        <div class="modal-block">
          <p><%= journey.user.email %></p>
          <p><%= journey.user.gender %></p>
          <p><%= journey.user.address %></p>
          <p><%= journey.user.birth_date %></p>
          <p><%= journey.user.phone %></p>
          <p><%= journey.user.contact ? "Non" : "Oui" %></p>
          <p><%= journey.detail.points_of_attention %></p>
        </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Fermer</button>
      </div>
    </div>
  </div>
</div>

app/views/journeys/create.html.erb
<h1>Journeys#create</h1>
<p>Find me in app/views/journeys/create.html.erb</p>

app/views/journeys/index.html.erb
<div class="journeys-index">
  <h1>Séjours</h1>
  <table class="table">
    <thead>
      <tr>
        <th>id</th>
        <th>user</th>
        <th>Départ</th>
        <th>Retour</th>
        <th>Provenance</th>
        <th>Nombre</th>
        <th>Destination</th>
        <th>Surprise</th>
        <th>Voiture</th>
        <th>Logement</th>
        <th>Activité</th>
        <th>Points d'attention</th>
      </tr>
    </thead>
    <tbody>
      <% i = 0 %>
      <% @journeys.each do |journey| %>
        <% if journey.status == "Paid" %>
          <% i += 1 %>
          <!-- data-target="#myModal" -->
          <tr data-toggle="modal<%= i %>" data-id="<%= i %>" >
            <td><%= journey.id %></td>
            <td class="journey-user"><%= journey.user.name + " " + journey.user.surname %></td>
            <td><%= journey.detail.start_date %></td>
            <td><%= journey.detail.end_date %></td>
            <td><%= journey.origin %></td>
            <td><%= journey.people_count %></td>
            <td><%= journey.destination_type %></td>
            <td><%= journey.detail.is_a_surprise ? "Oui":"Non" %></td>
            <td><%= journey.detail.travel_with_car ? "Oui":"Non" %></td>
            <td><%= journey.detail.housing_type %></td>
            <td><%= journey.detail.activity_type %></td>
            <td><button type="button" class="btn btn-outline-primary" data-toggle="modal" data-target="#myModal-<%= i %>">Infos client</button></td>
            <%= render partial:'user-info', locals: { i: i, journey: journey } %>
          </tr>
          <% end %>
      <% end %>
    </tbody>
  </table>
</div>

app/views/journeys/new.html.erb
<div id="home-banner">
  <div class="container">
    <div class="row">
      <div class="col-md-6">
        <div class="headline">
          <div class="empty-space"></div>
          <h1><span>Quand rien n'est prévu, tout est possible</span></h1>
          <p>La France authentique et inconnue à moins de 2h30 de chez vous, le temps d'un week-end.</p>
        </div>
      </div>
      <div class="col-md-2"></div>
      <div class="col-md-4">
        <div class="home-form text-center">
          <h2>I am a Franchouillard</h2>
          <div class="home-form-content">
            <%= simple_form_for @journey do |f| %>
              <%= f.input :origin, prompt: "D'où partez-vous ?", label: false, collection: ['Paris'], error: 'Veuillez indiquer votre lieu de départ.' %>
              <%= f.input :people_count, prompt: "Nombre de personnes", label: false, collection: ['1 trotteur', '2 trotteurs', '3 trotteurs', '4 trotteurs', '5 trotteurs', '6 trotteurs'], error: 'Dites-nous à combien vous désirez partir!' %>
              <%= f.input :destination_type, prompt: "Type de destination", label: false, collection: ['Ville', 'Mer', 'Campagne'], error: 'Allez, on est sûr que vous avez une petite préférence ;)' %>
              <%= f.submit "JE REDÉCOUVRE LE PAYS !", class: "btn btn-primary" %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<div id="how-banner" class="text-center">
  <h2>Comment Coq-trotter sereinement ?</h2>
  <p>Besoin d’un week-end et jamais d’idées ? De conquérir des villes magnifiques et peu connues ? Ou simplement de chiller pépouze à la mer dans un cadre inspirant dont vous n’avez jamais entendu parlé ?</p>
  <div class="how-pst">
    <div class="pst-image"></div>
    <div class="pst-summary">
      <div class="pst-line">
        <div class="pst-bullet">
          <i class="fa fa-train fa-style-1" aria-hidden="true"></i>
        </div>
        <div class="pst-text">2h30 max de train</div>
      </div>
      <div class="pst-line">
        <div class="pst-bullet">
          <i class="fa fa-bed fa-style-1" aria-hidden="true"></i>
        </div>
        <div class="pst-text">Une à trois nuits</div>
      </div>
      <div class="pst-line">
        <div class="pst-bullet">
          <i class="fa fa-thumbs-up fa-style-1" aria-hidden="true"></i>
        </div>
        <div class="pst-text">Lieu surprise d'exception</div>
      </div>
      <h2>À partir de 90€/pers</h2>
    </div>
  </div>
  <div class="how-steps fade-in">
    <div class="how-step text-center">
      <%= image_tag("calendar.png", height: 60)%>
      <h3>JE CONFIGURE MON TRAJET</h3>
      <p>Je saisis le nombre de voyageurs, mes dates, ainsi que le type d’environnement et de logement dans lequel je désire partir. De toute façon ça sera top 🚀</p>
    </div>
    <div class="how-step text-center">
      <%= image_tag("map.png", height: 60)%>
      <h3>JE DÉFINIS MES PRÉFÉRENCES</h3>
      <p>J’en profite pour préciser le genre de lieux que j’aimerais découvrir et si je désire réserver une activité sur place. L’équipe se chargera alors de vous préparer un trip aux petits oignons 👍</p>
    </div>
    <div class="how-step text-center">
      <%= image_tag("backpack.png", height: 60) %>
      <h3>SURPRISE 😍</h3>
      <p>C’est le week-end, à vous le grand air ! Un horaire, un train réservé par nos soins ou votre voiture… Vous voilà partis vers une destination qui ne vous sera révélée que 24h avant de prendre la route.</p>
    </div>
  </div>
  <%= link_to "JE PARS !", root_path(anchor: "home-banner"), class: "btn btn-primary btn-banner" %>
  <%= link_to "Dites m'en plus", root_path(anchor: "info-banner"), class: "more-link" %>
</div>
<div id="gift-banner">
  <div class="gift-content">
    <div class="gift-pst">
      <p>Vos proches aiment le camembert ?</p>
      <p>Découvrir de nouveaux endroits au charme fou ?</p>
      <p>Les soirées au coin du feu</p>
      <p>Les promenades sur les remparts</p>
    </div>
    <div class="gift-hk fade-in">
      <h2>OFFREZ LEUR UN WEEK-END SURPRISE !</h2>
      <p>A very french qualität séjour-cadeau qui saura les combler</p>
    </div>
    <%= image_tag("gift.png", height: 200, class: "gift-image fade-in") %>
  </div>
  <%= link_to "OFFRIR UN CADEAU", root_path(anchor: "home-banner"), class: "btn btn-primary btn-banner" %>
  <%= link_to "Comment faire un cadeau ?", pages_faq_path(anchor: "make-a-gift"), class: "more-link" %>
</div>
<div id="info-banner" class="text-center">
  <h2>Dates, transport et hébergement</h2>
  <div class="detail-cards fade-in">
    <div class="card card-dates">
      <i class="fa fa-clock-o fa-style-2" aria-hidden="true"></i>
      <h3>DATES</h3>
      <p>Choisissez de partir de une à trois nuits dans un créneau du jeudi au lundi compris.
      Tous nos départs s’effectuent à partir de 18h30 afin de vous permettre de profiter au maximum de votre virée franchouillarde, tout en respectant vos horaires de bureau.</p>
    </div>
    <div class="card card-transport">
      <i class="fa fa-train fa-style-2" aria-hidden="true"></i>
      <h3>TRANSPORT</h3>
      <p>Restez cool au moment de votre départ ! Toutes nos destinations sont atteignables en train ou voiture en moins de 2h30 pour plus de liberté d’esprit. Oubliez les longs trajets pour partir en week-end et laissez vous transporter.</p>
    </div>
    <div class="card card-housing">
      <i class="fa fa-bed fa-style-2" aria-hidden="true"></i>
      <h3>LOGEMENT</h3>
      <p>Au sein de chambres d’hôtes, de logements de choix, ou d’hôtels de charme en fonction de votre sélection. Nous mettons un point d’honneur à ce que vous ressentiez le terroir dès votre arrivée ! Vous pouvez dormir sur vos deux oreilles. Pour peu que celles-ci soient plates. Et horizontales.</p>
    </div>
    <div class="card card-activity">
      <i class="fa fa-bicycle fa-style-2" aria-hidden="true"></i>
      <h3>ACTIVITÉ OPTIONNELLE</h3>
      <p>Encore plus de surprise ! Envie d’un moment sportif un peu spécial, d’un dîner aux chandelles ou d’une visite croquignolesque ? Alors faites-nous part de vos préférence ! Avec ou sans option, un petit guide des joyeusetés locales vous sera envoyé par mail. </p>
    </div>
  </div>
  <%= link_to "JE RÉSERVE", root_path(anchor: "home-banner"), class: "btn btn-primary btn-banner" %>
  <%= link_to "Besoin de plus d'informations ?", pages_faq_path, class: "more-link" %>
</div>
<div id="testimonials-banner">
  <div class="testimonials-title">
    <h2>ILS AIMENT LE COQ TROTTEUR</h2>
    <h3>(...et on les aime aussi)</h3>
    <%= link_to 'Découvrir les témoignages', pages_testimonials_path, class: "button-link" %>
  </div>
  <div class="testimonials-car">
    <div class="t-one">
      <div class="quote-container">
        <blockquote>
          <p>Notre séjour avec le Coq Trotteur était formidable. Nous ne pensions pas découvrir autant de chose dans un endroit dont nous n'avions pourtant jamais entendu parlé !</p>
          <cite>Laura & Stéphanie</cite>
        </blockquote>
        <%= link_to 'Plus d\'opinions 💪', pages_testimonials_path, class: "home-link" %>
      </div>
    </div>
    <div class="t-two"></div>
    <div class="t-three"></div>
    <div class="t-four">
      <div class="quote-container">
        <blockquote>
          <p>Expérience de qualité, on se sent directement accueilli et l'on enchaine des découvertes dans une France que décisémment on ne connait pas si bien que ça. Une vraie déconnexion et plein de découvertes !</p>
          <cite>Jérémy</cite>
        </blockquote>
        <%= link_to 'Voir d\'autres avis 👌', pages_testimonials_path, class: "home-link" %>
      </div>
    </div>
  </div>
</div>
<div id="label-banner">
  <%= image_tag 'aspt.png', class: "label-image" %>
  <h3>Le Coq Trotteur est accrédité ASPT</h3>
</div>

app/views/journeys/show.html.erb
<div id="summary-banner">
  <div class="summary-block">
    <div class="summary-content">
      <h2>Votre réservation</h2>
      <h3 style="margin-bottom: 10px;"><%= @journey.people_count.to_i %> voyageurs au départ de <%= @journey.origin %> le <%= @journey.detail.start_date %></h3>
      <h3 style="margin-top: 0;"><%= @journey.detail.is_a_surprise ? "Séjour surprise !" : "" %></h3>
      <h4>Numéro de commande</h4>
        <p>N<%= @journey.id %>LCT</p>
      <h4>Statut</h4>
        <% if @journey.status == "Paid" %>
          <p>À venir </p>
        <% else %>
          <p>Terminé</p>
        <% end %>
      <h4>Nom de réservation</h4>
        <p><%= @journey.user.surname %> <%= @journey.user.name %></p>
        <p><%= @journey.user.address %></p>
        <p><%= @journey.user.email %></p>
        <p><%= @journey.user.phone %></p>
      <h4>Détails</h4>
        <p><%= @journey.detail.housing_type %></p>
        <p><%= @journey.detail.activity_type ? "Activité : " + @journey.detail.activity_type : "Aucune activité sélectionnée" %></p>
        <% if @journey.detail.points_of_attention %>
          <p>Points d'attentions :</p>
          <p><%= @journey.detail.points_of_attention %></p>
        <% end %>
      <div class="summary-price">
        <h4>TOTAL</h4>
        <h4><%= @journey.people_count.to_i * @journey.detail.price.cents / 100 %>€</h4>
      </div>
    </div>
  </div>
  <%= link_to '> Retour à l\'accueil', root_path, class: "home-link", style: "text-align: center;" %>
</div>

app/views/journeys/summary.html.erb
<div id="step-bar">
  <div class="all-steps">
    <div class="step">
      <p>☝</p>
      <h3>1 - Séjour</h3>
    </div>
    <div class="step">
      <p>✌</p>
      <h3>2 - Voyageurs</h3>
    </div>
    <div class="step active-step">
      <p>👏</p>
      <h3>3 - Validation</h3>
    </div>
  </div>
  <div class="price">
    <h4>90€</h4>
  </div>
</div>
<div id="details-banner">
  <div class="details-form">
    <div class="details-form-content">
      <h2>Vous partez en week-end !</h2>
      <h3><%= @journey.people_count[/[123456789]/] %> voyageurs au départ de <%= @journey.origin %> le <%= @journey.detail.date %></h3>
      <p><%= @journey.detail.is_a_surprise ? "Ce séjour est une surprise !" : "" %></p>
      <h4>Numéro de commande</h4>
      <p>N<%= @journey.id %>LCT</p>
      <h4>Nom de réservation</h4>
      <p><%= @journey.client.gender %> <%= @journey.client.surname %> <%= @journey.client.name %></p>
      <p><%= @journey.client.address %></p>
      <p><%= @journey.client.mail %></p>
      <p><%= @journey.client.phone %></p>
      <h4>Détails</h4>
      <p><%= @journey.detail.housing_type %></p>
      <p><%= @journey.detail.activity_type ? "Vous avez sélectionné un chouette moment de " + @journey.detail.activity_type : "Pas d'activité sélectionnée" %></p>
      <% if @journey.detail.points_of_attention %>
        <p>Points d'attentions (promis, on fera attention !) :</p>
        <p><%= @journey.detail.points_of_attention %></p>
      <% end %>
    </div>
  </div>
</div>